version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    environment:
      - START_XVFB=false  # для --headless-режиме можно поставить в false
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true  # позволяет запустить больше сессий на одной ноде селениума
      - SE_NODE_MAX_SESSIONS=16  # поставил по количеству потоков процессора
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING  # должно отключать логи селениума, но не работает?
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps= # должно убирать спам в логи с сообщением [99]
    ports:
      - "4444:4444"
    restart: always
    networks:
      - selenium_network

  pw-registration-bot:
    image: malkiz/pw-registration-bot
    restart: always
    deploy:
      replicas: 10
    volumes:
      - ./app/accounts:/app/accounts
    command: sh -c "python3 registration_pw_accounts.py"
    depends_on:
      - selenium
    networks:
      - selenium_network

networks:
  selenium_network:
    ipam:
      driver: default
      config:
        - subnet: 172.65.0.0/16