version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome:3.141.59
    shm_size: 2g  # рекомендовано 2g, но на 10 нод я упирался в память
    environment:
      - TZ=Europe/Moscow
      - START_XVFB=false  # для --headless-режиме можно поставить в false
      - NODE_OVERRIDE_MAX_SESSIONS=true  # позволяет запустить больше сессий на одной ноде Selenium
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=5  # не меньше количества инстансов?
      # должно отключать логи Selenium и убирать спам ошибки "[99]"
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING -Dwebdriver.chrome.whitelistedIps=
    ports:
      - "4444"
    restart: always
    networks:
      - pw-autoreg_selenium

  app:
    image: malkiz/pw-autoreg
    restart: always
    env_file:
      - .env
    deploy:
      replicas: 5
    volumes:
      - pw-accounts:/app/accounts
      - registrations-debug-screenshots:/app/screenshots
    depends_on:
      - selenium
    networks:
      - pw-autoreg_redis  # external network
      - pw-autoreg_selenium

volumes:
  pw-accounts:
    name: pw-accounts
  registrations-debug-screenshots:
    name: registrations-debug-screenshots

networks:
  pw-autoreg_redis:
    external: true
  pw-autoreg_selenium:
