version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g  # рекомендовано 2g, но на 10 нод я упирался в память
    environment:
      - TZ=Europe/Moscow
      - START_XVFB=false  # для --headless-режиме можно поставить в false
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true  # позволяет запустить больше сессий на одной ноде Selenium
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5  # не меньше количества инстансов
      # должно отключать логи Selenium и убирать спам ошибки "[99]"
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING -Dwebdriver.chrome.whitelistedIps=
    ports:
      - "4444" # 4444:4444, если нужно выставить порт наружу
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6379" # 6379:6379, если нужно выставить порт наружу

  app:
    image: malkiz/pw-autoreg
    restart: always
    env_file:
      - .env
    deploy:
      replicas: 5
    volumes:
      - pw-accounts:/app/accounts
      - registrations-debug-screenshots:/app/screenshots
    depends_on:
      - selenium
      - redis

volumes:
  pw-accounts:
    name: pw-accounts
  registrations-debug-screenshots:
    name: registrations-debug-screenshots
